---
title: "Final Project"
author: "Navan Powers & Andrew Graham"
date: "8/10/2021"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(scales)
library(lubridate)
library(strucchange)
library(sjmisc)
library(zoo)
library(knitr)
library(markdown)
options(dplyr.summarise.inform = FALSE)

```

```{r}
#Import and Clean Data for All Colorado
dat<-read.csv("0521_MJSalesHistoricalReport.csv")
dat.trim<-data.frame(select(dat,Month,Medical,Retail,Total))

dat.CO <- data.frame(matrix(nrow=length(dat.trim$Month),ncol=0))
#Set Value types
dat.CO$Medical <- as.numeric(dat.trim$Medical)
dat.CO$Retail <- as.numeric(dat.trim$Retail)
dat.CO$Total <- as.numeric(dat.trim$Total)
dat.CO$Month <- as.Date(dat.trim$Month, format = "%m/%d/%Y")

#Convert Data to Tall format
dat.CO.long<-dat.CO %>%
  pivot_longer(!Month, names_to = "Type", values_to = "Sales")

#Date of Pandemic Lockdown Start
PStart <- as.Date("2020-03-01")
PStart.point <- which(grepl(PStart, dat.CO$Month))

#Confidence interval for Chow
psig <- .05
```


```{r}
#plot Initial Data
g<-ggplot(dat.CO.long,aes(x=Month, y=Sales, color = Type ))+geom_line()+
  scale_y_continuous(labels=scales::dollar_format(),limits=c(0,250000000))+
  ggtitle("Colorado Marijuana Sales")
g


#Plot All CO data with March Lockdown Line at March 2021
g<-g+geom_vline(xintercept=PStart)+
  geom_text(aes(x=PStart, label="Post-Lockdowns", y=230000000), colour="blue", angle=90, vjust = 1.2, size=2)+
  geom_text(aes(x=PStart, label="Pre-Lockdowns", y=230000000), colour="red", angle=90, vjust = -1, size=2)+
  geom_text(aes(x=PStart, label="March - 2021", y=10), colour="black", size=3)

g
```


#Split Data into Retail and Medical then perform Chow test to determine if there is a break point...
#Null hypothesis being that one regression line fits the data better than two divided at the break point

```{r}
#Import Retail as Time Series
ts_Rsales <- ts(dat.CO$Retail,frequency=12,start=c(2014,1))

ts.plot(ts_Rsales,xlab='Date',ylab='Sales',main='Retail Marijuana Sales')
abline(v=2020.3)

#De-seasonalize the Data
dec_Rsales <- decompose(ts_Rsales,"additive")
adj_Rsales <- ts_Rsales - dec_Rsales$seasonal
plot(adj_Rsales,xlab='Date',ylab='Sales',main='Adjusted Retail Marijuana Sales')
abline(v=2020.3)

#Run Chow Test  at point 75 (March 2020)
n<- length(adj_Rsales)
Trend <- c(1:n)
sctest(adj_Rsales~Trend, type = "Chow", point = PStart.point)

#P-value really low,  evidence of change
```

#Best Fit Lines
```{r}
dat.CO$Retail <- adj_Rsales[1:length(adj_Rsales)]
dat.CO <- data.frame(select(dat.CO,Month,Retail))

dat.CO.long<-dat.CO %>%
  pivot_longer(!Month, names_to = "Type", values_to = "Sales")

m.trim<-lm(Retail~Month,data=dat.CO)
pre.trim<-lm(Retail~Month,data=subset(dat.CO,Month<as.Date("2020-3-1")))
post.trim<-lm(Retail~Month,data=subset(dat.CO,Month>=as.Date("2020-3-1")))
# summary(m.trim)
# summary(pre.trim)
# summary(post.trim)
m.trim$coefficients[1]
m.trim$coefficients[2]
pre.trim$coefficients[1]
pre.trim$coefficients[2]
post.trim$coefficients[1]
post.trim$coefficients[2]
#plot Initial Data
g<-ggplot(dat.CO.long,aes(x=Month, y=Sales, color = Type ))+geom_line()+xlab("")+
  scale_y_continuous(labels=scales::dollar_format(),limits=c(0,250000000))+
  scale_color_manual(values = c("blue", "red","purple")) +
  ggtitle("Colorado Marijuana Adj Sales")
g

#linear model for total range Retail
g+stat_smooth(data=subset(dat.CO.long,Type=="Retail"),method = "lm", formula=y~x,se = FALSE)+
  # stat_regline_equation(data=subset(dat.CO.long,Type=="Retail"),label.y = 225000000,aes(label = ..eq.label..))+
  stat_regline_equation(data=subset(dat.CO.long,Type=="Retail"),label.y = 250000000,aes(label = ..rr.label..))
  # +labs(subtitle=paste("Slope = ", round(m.trim$coefficients[2],0)))

#linear model for pre-covid range Retail
g+stat_smooth(data=subset(dat.CO.long,Type=="Retail" & Month<=as.Date("2020-3-1")), method = "lm", formula=y~x,se = FALSE)+
  # stat_regline_equation(data=subset(dat.CO.long,Type=="Retail" & Month<as.Date("2020-3-1")),label.y = 225000000,aes(label = ..eq.label..))+
  stat_regline_equation(data=subset(dat.CO.long,Type=="Retail" & Month<=as.Date("2020-3-1")),label.y = 250000000,aes(label = ..rr.label..))
  # +labs(subtitle=paste("Slope = ", round(pre.trim$coefficients[2],0)))

#linear model for covid range Retail
g+stat_smooth(data=subset(dat.CO.long,Type=="Retail" & Month>=as.Date("2020-3-1")), method = "lm", formula=y~x,se = FALSE)+
  # stat_regline_equation(data=subset(dat.CO.long,Type=="Retail" & Month>=as.Date("2020-3-1")),label.y = 225000000,aes(label = ..eq.label..))+
  stat_regline_equation(data=subset(dat.CO.long,Type=="Retail" & Month>=as.Date("2020-3-1")),label.y = 250000000,aes(label = ..rr.label..))
  # +labs(subtitle=paste("Slope = ", round(post.trim$coefficients[2],0)))

#piecewise linear model for pre-covid and covid ranges Retail
g<-g+stat_smooth(data=subset(dat.CO.long,Type=="Retail" & Month<=as.Date("2020-3-1")), method = "lm", formula=y~x,se = FALSE)+
stat_smooth(data=subset(dat.CO.long,Type=="Retail" & Month>=as.Date("2020-3-1")), method = "lm", formula=y~x,se = FALSE)


#Plot All CO data with March Lockdown Line at March 2021
g<-g+geom_vline(xintercept=PStart)+
  geom_text(aes(x=PStart, label="Post-Lockdowns", y=230000000), colour="blue", angle=90, vjust = 1.2, size=2.5)+
  geom_text(aes(x=PStart, label="Pre-Lockdowns", y=230000000), colour="red", angle=90, vjust = -1, size=2.5)+
  geom_text(aes(x=PStart, label="March - 2021", y=10), colour="black", size=3)
g


```







## Examin Covid cases

```{r}
#Import and Clean Data for All Colorado during pandemic time period
dat<-read.csv("pandemic.csv")
dat.pan<-data.frame(select(dat,Month,Medical,Retail,Total,Covid.Cases))
dat.z<-data.frame(select(dat,Month,Medical,Retail,Total,Covid.Cases))
#scalar for plotting covid numbers
scl=150
#scale covid data for plotting
dat.z$Covid.Cases <- dat.pan$Covid.Cases*scl
#Set month data as date type
dat.z$Month <- as.Date(dat.pan$Month, format = "%m/%d/%Y")
#Convert Data to Tall format
dat.z.long<-dat.z %>%
  pivot_longer(!Month, names_to = "Type", values_to = "Sales")

#plot Pandemic-Time Data
g<-ggplot(dat.z.long,aes(x=Month, y=Sales)) + 
            geom_line(aes(color = Type, linetype = Type %in% c("Covid.Cases"))) + 
            scale_linetype_manual(values = c("TRUE" = "twodash", "FALSE" = "solid")) +
            scale_y_continuous(labels=scales::dollar_format(),limits=c(0,250000000),
                               sec.axis = sec_axis(~./scl,name = "Covid Cases",labels = comma)) + 
            guides(linetype = "none", size = "none") +
            scale_color_manual(values = c("purple", "red", "blue","black")) +
            ggtitle("Colorado Marijuana Sales After Covid Start")
g
```




#Import County Data



```{r}
#import and Clean Retail Counties
d<-read.csv("Marijuana_County_Retail.csv")
d<-set_na(d, na = c("NR"))
d$Month <-as.Date(dat.trim$Month, format = "%m/%d/%Y")
for(i in 2:ncol(d)){
  d[,i] <- as.numeric(d[,i])
}
dat.county.retail<-d

```


#Analyze Retail
```{r}
#Retail  Find P-value on chow test for all counties with at least a year of data before March 2020
Rcol <- colnames(dat.county.retail)

df <- data.frame(County=character(),DataPoints=integer(),PValue=double(),Reject_Null=logical())

n<- length(dat.county.retail$Month)
Trend <- c(1:n)

for (i in 2:ncol(dat.county.retail)){
  d <- dat.county.retail[,i]
  na_to_point <- sum(is.na(d[1:75]))
  adj_point <- PStart.point-na_to_point
  
  df[i-1,1] <- Rcol[i]
  df[i-1,2] <- n - sum(is.na(d[1:n]))
  
  
  
  
  if(adj_point < 12){
    df[i-1,3] <- NA
    df[i-1,4] <- NA
  } else {
    t <- ts(d,frequency=12,start=c(2014,1))
    s <- sctest(t~Trend, type = "Chow", point = adj_point)
    df[i-1,3] <- s$p.value
    df[i-1,4] <- s$p.value < psig
    ts.plot(t,xlab='Date',ylab='Sales',main=paste(colnames(dat.county.retail[i]),' County Retail Marijuana Sales\n','P-value = ',s$p.value))
    abline(v=2020.3)
  }
 
}

df

#sum(df$Reject_Null)/(length(Rcol)-1-sum(is.na(df$PValue)))
#ncol(dat.county.retail)
```


